# Generated by Django 5.1 on 2024-08-22 16:19

import django.db.models.deletion
import posters_app.business_logic.poster_currency_logic
import posters_app.business_logic.poster_image_name_logic
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('header', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=5, max_digits=9)),
                ('currency', models.CharField(max_length=3, validators=[posters_app.business_logic.poster_currency_logic.validate_currency])),
                ('client', models.ForeignKey(blank=True, db_column='client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_posters', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posters_app.postercategories')),
            ],
        ),
        migrations.CreateModel(
            name='PosterImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to=posters_app.business_logic.poster_image_name_logic.GetUniqueImageName(), validators=[posters_app.business_logic.poster_image_name_logic.validate_image_size])),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porter_images', to='posters_app.poster')),
            ],
        ),
    ]
