# Generated by Django 5.1 on 2024-08-23 10:56

import django.db.models.deletion
import posters_app.business_logic.phone_number_logic
import posters_app.business_logic.poster_currency_logic
import posters_app.business_logic.poster_image_name_logic
# import posters.posters_app.business_logic.poster_image_name_logic
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters_app', '0001_initial'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[posters_app.business_logic.phone_number_logic.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='posterimages',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to=posters_app.business_logic.poster_image_name_logic.GetUniqueImageName(media_subdirectory='poster_images'), validators=[posters_app.business_logic.poster_image_name_logic.validate_image_size]),
        ),
        migrations.CreateModel(
            name='PosterLite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20, validators=[posters_app.business_logic.phone_number_logic.validate_phone_number])),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('header', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=5, max_digits=9)),
                ('currency', models.CharField(max_length=3, validators=[posters_app.business_logic.poster_currency_logic.validate_currency])),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posters_app.postercategories')),
                ('client', models.ForeignKey(blank=True, db_column='client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_posters_lite', to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='PosterLiteImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to=posters_app.business_logic.poster_image_name_logic.GetUniqueImageName(media_subdirectory='poster_lite_images'), validators=[posters_app.business_logic.poster_image_name_logic.validate_image_size])),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porterLite_images', to='posters_app.posterlite')),
            ],
        ),
    ]
