# Generated by Django 5.1 on 2024-08-25 20:18

import posters_app.business_logic.poster_image_name_logic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters_app', '0002_alter_poster_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posterimages',
            name='image_path',
            field=models.ImageField(blank=True, default='poster_images/default_image.png', null=True, upload_to=posters_app.business_logic.poster_image_name_logic.GetUniqueImageName(media_subdirectory='poster_images'), validators=[posters_app.business_logic.poster_image_name_logic.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='posterlite',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='posterliteimages',
            name='image_path',
            field=models.ImageField(blank=True, default='poster_images/default_image.png', null=True, upload_to=posters_app.business_logic.poster_image_name_logic.GetUniqueImageName(media_subdirectory='poster_lite_images'), validators=[posters_app.business_logic.poster_image_name_logic.validate_image_size]),
        ),
    ]
