# Generated by Django 5.1 on 2024-08-31 15:17

import posters_app.business_logic.poster_currency_logic
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters_app', '0006_alter_poster_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='currency',
            field=models.CharField(choices=[('USD', 'Us Dollar'), ('EUR', 'Euro'), ('RUB', 'Russian Rubble'), ('GBP', 'British pound')], max_length=3, validators=[posters_app.business_logic.poster_currency_logic.validate_currency]),
        ),
    ]
