# Generated by Django 5.1 on 2024-09-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters_app', '0008_alter_posterimages_poster_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posterliteimages',
            name='poster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posterLite_images', to='posters_app.posterlite'),
        ),
    ]
